name: Build

on:
  push:
    branches: [ legacy ]
  pull_request:
    branches: [ legacy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Setup Forge workspace
        run: ./gradlew setupCiWorkspace

      - name: Build project
        run: ./gradlew build

      - name: Show build output
        run: ls -lh build/libs

      - name: Rename jar
        run: mv build/libs/*.jar build/libs/LiquidBounce-build.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LiquidBounce
          path: build/libs/LiquidBounce-build.jar
